// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0027:Use expression body for accessor")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration")]
[assembly: SuppressMessage("Style", "IDE0025:Use expression body for property")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method")]
[assembly: SuppressMessage("Style", "IDE0032:Use auto property")]
[assembly: SuppressMessage("Style", "IDE0054:Use compound assignment")]
[assembly: SuppressMessage("Style", "IDE0251:Make member 'readonly'")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching")]
[assembly: SuppressMessage("Style", "IDE0020:Use pattern matching")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructor")]
[assembly: SuppressMessage("Style", "IDE0024:Use expression body for operator")]
[assembly: SuppressMessage("Style", "IDE0030:Use coalesce expression")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization")]
[assembly: SuppressMessage("Style", "IDE0031:Use null propagation")]
[assembly: SuppressMessage("Style", "IDE0034:Simplify 'default' expression")]
[assembly: SuppressMessage("Style", "IDE0038:Use pattern matching")]
[assembly: SuppressMessage("Style", "IDE0039:Use local function")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression")]
[assembly: SuppressMessage("Style", "IDE0049:Simplify Names")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members")]
[assembly: SuppressMessage("Style", "IDE0053:Use expression body for lambda expression")]
[assembly: SuppressMessage("Style", "IDE0057:Use range operator")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement")]
[assembly: SuppressMessage("Style", "IDE0066:Convert switch statement to expression")]
[assembly: SuppressMessage("Style", "IDE0070:Use 'System.HashCode'")]
[assembly: SuppressMessage("Style", "IDE0074:Use compound assignment")]
[assembly: SuppressMessage("Style", "IDE0078:Use pattern matching")]
[assembly: SuppressMessage("Style", "IDE0083:Use pattern matching")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'")]
[assembly: SuppressMessage("Style", "IDE0270:Use coalesce expression")]
[assembly: SuppressMessage("Style", "IDE1005:Delegate invocation can be simplified.")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles")]
[assembly: SuppressMessage("Style", "IDE2000:Avoid multiple blank lines")]
[assembly: SuppressMessage("Style", "IDE2001:Embedded statements must be on their own line")]
[assembly: SuppressMessage("Style", "IDE2002:Consecutive braces must not have blank line between them")]
[assembly: SuppressMessage("Style", "IDE2003:Blank line required between block and subsequent statement")]
[assembly: SuppressMessage("Performance", "UNT0001:Empty Unity message")]
[assembly: SuppressMessage("Correctness", "UNT0007:Null coalescing on Unity objects")]
[assembly: SuppressMessage("Type Safety", "UNT0010:Component instance creation")]
[assembly: SuppressMessage("Type Safety", "UNT0014:Invalid type for call to GetComponent")]
[assembly: SuppressMessage("Performance", "UNT0022:Inefficient position/rotation assignment")]
[assembly: SuppressMessage("Performance", "UNT0024:Give priority to scalar calculations over vector calculations")]
[assembly: SuppressMessage("Correctness", "UNT0033:Incorrect message case")]
[assembly: SuppressMessage("Style", "IDE0180:Use tuple to swap values")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Remove unread private members")]
